---
language: ruby
cache: bundler
sudo: false

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock

jobs:
  allow_failures:
    - env: STRICT_VARIABLES=yes TRUSTED_NODE_DATA=yes PUPPET_VERSION="~> 5.0"

  include:
    - stage: check
      rvm: 2.4.1
      script:
        - bundle exec rake pkg:compare_latest_tag
        - bundle exec rake pkg:create_tag_changelog

    - stage: deploy
      rvm: 2.4.1
      script:
        - true
      before_deploy:
        - "export SPECFILE_VERSION=`rpm -q --specfile build/*.spec --queryformat '%{VERSION}'`"
        - '[[ $TRAVIS_TAG =~ ^${SPECFILE_VERSION}$ ]]'
      deploy:
        - provider: releases
          api_key:
              secure: "pv/fukBibZQJKScSQxJvPG4jSbGpBdxvIbp7K4JT2VRx0mIdHMQZl0HQoH++pHqiw1Xn2YcmLlqEwVC7HMndG/tQIAt3tZwp9mPJVDAZx9+jRBVhPvNjJg/Uy8tQzekualNRgnoo8VOZeurLdv53hFWVUoWjhJ7Ep6KO57pQu5KcgjxXYBx9cd9fbsTGNJwghfrkKGjKLe71lJsFeuf5FNQztTDT627Rme9T/fLmqaJkDj3FqyomfDlEvVmoWFc+6I492Ec9Z7A2As/J5YNcDzXI72if1ygB4vPYu0idCuuHRc1Y9TLyD/xNJpYt+2COqtVvHZNEXht2L/NQyAGLcfgCzfFZBzoYTrnOwKFAo0+aVVoO0MhMKvenr/vkpYALeM1po4f9IodSD8FTQpDR8BfXVLU5gG8CiPAhcm8X74znx1NSJ/kSZC1FX34Q28zRCuMi7G/2CxTfbHxy//1yGmB970nJ/J673Zgw77oo5kdRf0pS5ZUUXK4aUguEJGaTYyzU5bL4phanYGaxlWuVERNZbjpMdfV1Diszgn+u4sl+dOHpa0P/B0NkOgKlGtR6o1fCHoSYv2GSJ3N3MQlIeMWu0Rjxx8U3R8OAxVe+NbwycP71hPGEWyiEmzY8nZuYlYr58FY2658ITIa9/OF9gGEmftnknM0h5fpHA0aufqA="
          skip_cleanup: true
          on:
            tags: true
            condition: '($SKIP_PUBLISH != true)'
